### ISSUE TITLE
0.4.0 release TODO list

### ISSUE THREAD

**Issue by guruofquality** [pothosware/pothos-gui#118]
* [ ] Tutorial should use the new drag to connect method
* [ ] Tutorial images should use inline sig/slot ports
* [ ] Document reload feature in Tutorial
* [ ] Document export to JSON in Tutorial
